"""Add activation_token to users

Revision ID: 130bde8c058a
Revises: d7b55ebddb5b
Create Date: 2025-09-18 17:51:45.862827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130bde8c058a'
down_revision = 'd7b55ebddb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('activation_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('activation_token_expiry')
        batch_op.drop_column('activation_token')

    # ### end Alembic commands ###
